/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rjp_fastframework_Hello */

#ifndef _Included_com_rjp_fastframework_Hello
#define _Included_com_rjp_fastframework_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rjp_fastframework_Hello
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rjp_fastframework_Hello_sayHi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
